wep_att = { }

--wep_att[ classname ] = { [ attachmentname ] = { attachmenttype, price } }
--//RedPrimaries
wep_att[ "cw_kk_ins2_ak74" ] = {
    [ "kk_ins2_kobra" ] =       { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =      { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =    { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =       { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =         { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_pbs1" ] =        { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_vertgrip" ] =    { "Under", 150, unlocked, 7 },
    [ "kk_ins2_gl_gp25" ] =     { "Under", 250, unlocked, 8 },
    [ "kk_ins2_lam" ] =         { "Lasers", 100, unlocked, 9 },
    [ "kk_ins2_flashlight" ] =  { "Lasers", 150, unlocked, 10 },
    [ "kk_ins2_anpeq15" ] =     { "Lasers", 200, unlocked, 11 },
    [ "am_magnum" ] =           { "Ammo", 200, unlocked, 12 },
    [ "am_matchgrade" ] =       { "Ammo", 250, unlocked, 13 }
}
wep_att[ "cw_kk_ins2_akm" ] = {
    [ "kk_ins2_kobra" ] =       { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =      { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =    { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =       { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =         { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_pbs1" ] =        { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_vertgrip" ] =    { "Under", 150, unlocked, 7 },
    [ "kk_ins2_gl_gp25" ] =     { "Under", 250, unlocked, 8 },
    [ "kk_ins2_lam" ] =         { "Lasers", 100, unlocked, 9 },
    [ "kk_ins2_flashlight" ] =  { "Lasers", 150, unlocked, 10 },
    [ "kk_ins2_anpeq15" ] =     { "Lasers", 200, unlocked, 11 },
    [ "am_magnum" ] =           { "Ammo", 200, unlocked, 12 },
    [ "am_matchgrade" ] =       { "Ammo", 250, unlocked, 13 }
}
wep_att[ "cw_kk_ins2_aks74u" ] = {
    [ "kk_ins2_kobra" ] =       { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =      { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =    { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =       { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =         { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_pbs1" ] =        { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_vertgrip" ] =    { "Under", 150, unlocked, 7 },
    [ "kk_ins2_lam" ] =         { "Lasers", 100, unlocked, 8 },
    [ "kk_ins2_flashlight" ] =  { "Lasers", 150, unlocked, 9 },
    [ "kk_ins2_anpeq15" ] =     { "Lasers", 200, unlocked, 10 },
    [ "am_magnum" ] =           { "Ammo", 200, unlocked, 11 },
    [ "am_matchgrade" ] =       { "Ammo", 250, unlocked, 12 }
}
wep_att[ "cw_kk_ins2_fnfal" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_scope_mosin" ] =     { "Sight", 250, unlocked, 6 },
    [ "kk_ins2_suppressor_ins" ] =  { "Barrel", 150, unlocked, 7 },
    [ "kk_ins2_bipod" ] =           { "Under", 150, unlocked, 8 },
    [ "kk_ins2_vertgrip" ] =        { "Under", 150, unlocked, 9 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 10 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 11 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 12 },
    [ "kk_ins2_mag_fal_30" ] =      { "Miscellaneous", 150, unlocked, 13 },
    [ "kk_ins2_fnfal_skin" ] =      { "Miscellaneous", 50, unlocked, 14 },
    [ "kk_ins2_fnfal_skin2" ] =     { "Miscellaneous", 50, unlocked, 15 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 16 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 17 }
}
wep_att[ "cw_kk_ins2_m1a1" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_suppressor_ins" ] =  { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_vertgrip" ] =        { "Under", 150, unlocked, 7 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 8 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 9 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 10 },
    [ "kk_ins2_mag_m1a1_30" ] =     { "Miscellaneous", 150, unlocked, 11 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 12 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 13 }
}
wep_att[ "cw_kk_ins2_m1a1_para" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_suppressor_ins" ] =  { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_vertgrip" ] =        { "Under", 150, unlocked, 7 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 8 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 9 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 10 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 11 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 12 }
}
wep_att[ "cw_kk_ins2_mosin" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_scope_mosin" ] =     { "Sight", 250, unlocked = true, 6 },
    [ "kk_ins2_suppressor_ins" ] =  { "Barrel", 150, unlocked, 7 },
    [ "kk_ins2_bipod" ] =           { "Under", 150, unlocked, 8 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 9 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 10 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 11 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 12 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 13 }
}
wep_att[ "cw_kk_ins2_mp40" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_suppressor_ins" ] =  { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 7 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 8 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 9 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 10 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 11 }
}
wep_att[ "cw_kk_ins2_rpk" ] = {
    [ "kk_ins2_kobra" ] =       { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =      { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =    { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =       { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =         { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_pbs1" ] =        { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_lam" ] =         { "Lasers", 100, unlocked, 7 },
    [ "kk_ins2_flashlight" ] =  { "Lasers", 150, unlocked, 8 },
    [ "kk_ins2_anpeq15" ] =     { "Lasers", 200, unlocked, 9 },
    [ "am_magnum" ] =           { "Ammo", 200, unlocked, 10 },
    [ "am_matchgrade" ] =       { "Ammo", 250, unlocked, 11 }
}
wep_att[ "cw_kk_ins2_sks" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_scope_mosin" ] =     { "Sight", 250, unlocked, 6 },
    [ "kk_ins2_pbs1" ] =            { "Barrel", 150, unlocked, 7 },
    [ "kk_ins2_bipod" ] =           { "Under", 150, unlocked, 8 },
    [ "kk_ins2_vertgrip" ] =        { "Under", 150, unlocked, 9 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 10 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 11 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 12 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 13 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 14 }
}
wep_att[ "cw_kk_ins2_sterling" ] = {
    [ "kk_ins2_kobra" ] =               { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =              { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =            { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =               { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =                 { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_suppressor_sterling" ] = { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_lam" ] =                 { "Lasers", 100, unlocked, 7 },
    [ "kk_ins2_flashlight" ] =          { "Lasers", 150, unlocked, 8 },
    [ "kk_ins2_anpeq15" ] =             { "Lasers", 200, unlocked, 9 },
    [ "am_magnum" ] =                   { "Ammo", 200, unlocked, 10 },
    [ "am_matchgrade" ] =               { "Ammo", 250, unlocked, 11 }
}
wep_att[ "cw_kk_ins2_toz" ] = {
    [ "kk_ins2_kobra" ] =               { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =              { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =            { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_suppressor_shotgun" ] =  { "Barrel", 150, unlocked, 4 },
    [ "kk_ins2_vertgrip" ] =            { "Under", 150, unlocked, 5 },
    [ "kk_ins2_lam" ] =                 { "Lasers", 100, unlocked, 6 },
    [ "kk_ins2_flashlight" ] =          { "Lasers", 150, unlocked, 7 },
    [ "kk_ins2_anpeq15" ] =             { "Lasers", 200, unlocked, 8 },
    [ "am_slugrounds" ] =               { "Ammo", 200, unlocked, 9 },
    [ "am_flechetterounds" ] =          { "Ammo", 200, unlocked, 10 }
}
--//BluePrimaries
wep_att[ "cw_kk_ins2_mini14" ] = { -- AC-556
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_suppressor_sec" ] =  { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_hoovy" ] =           { "Barrel", 150, unlocked, 7 },
    [ "kk_ins2_vertgrip" ] =        { "Under", 150, unlocked, 8 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 9 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 10 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 11 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 12 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 13 }
}
wep_att[ "cw_kk_ins2_galil" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_suppressor_ins" ] =  { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_hoovy" ] =           { "Barrel", 150, unlocked, 7 },
    [ "kk_ins2_bipod" ] =           { "Under", 150, unlocked, 8 },
    [ "kk_ins2_vertgrip" ] =        { "Under", 250, unlocked, 9 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 10 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 11 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 12 },
    [ "kk_ins2_mag_galil_75" ] =    { "Miscellaneous", 250, unlocked, 13 },
    [ "kk_ins2_galil_sar" ] =       { "Miscellaneous", 250, unlocked, 14 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 15 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 16 }
}
wep_att[ "cw_kk_ins2_cstm_galil_ace" ] = {
    [ "kk_ins2_cstm_cmore" ] =      { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_cstm_barska" ] =     { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_suppressor_sec" ] =  { "Barrel", 150, unlocked, 4 },
    [ "kk_ins2_bipod" ] =           { "Under", 150, unlocked, 5 },
    [ "kk_ins2_vertgrip" ] =        { "Under", 250, unlocked, 6 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 7 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 8 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 9 },
    [ "kk_ins2_mag_galil_75" ] =    { "Miscellaneous", 250, unlocked, 10 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 11 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 12 }
}
wep_att[ "cw_kk_ins2_mp5k" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_suppressor_sec" ] =  { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 7 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 8 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 9 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 10 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 11 }
}
wep_att[ "cw_kk_ins2_ump45" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_suppressor_sec" ] =  { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 7 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 8 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 9 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 10 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 11 }
}
wep_att[ "cw_kk_ins2_l1a1" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_scope_mosin" ] =     { "Sight", 250, unlocked, 6 },
    [ "kk_ins2_suppressor_sec" ] =  { "Barrel", 150, unlocked, 7 },
    [ "kk_ins2_bipod" ] =           { "Under", 150, unlocked, 8 },
    [ "kk_ins2_vertgrip" ] =        { "Under", 150, unlocked, 9 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 10 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 11 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 12 },
    [ "kk_ins2_mag_fal_30" ] =      { "Miscellaneous", 150, unlocked, 13 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 14 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 15 }
}
wep_att[ "cw_kk_ins2_m14" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_scope_m40" ] =       { "Sight", 250, unlocked, 6 },
    [ "kk_ins2_suppressor_sec" ] =  { "Barrel", 150, unlocked, 7 },
    [ "kk_ins2_hoovy" ] =           { "Barrel", 150, unlocked, 8 },
    [ "kk_ins2_bipod" ] =           { "Under", 150, unlocked, 9 },
    [ "kk_ins2_vertgrip" ] =        { "Under", 150, unlocked, 10 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 11 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 12 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 13 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 14 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 15 }
}
wep_att[ "cw_kk_ins2_m16a4" ] = {
    [ "bg_foldsight" ] =            { "Sight", 50, unlocked, 1 },
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 3 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 4 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 6 },
    [ "kk_ins2_scope_m40" ] =       { "Sight", 250, unlocked, 7 },
    [ "kk_ins2_suppressor_sec" ] =  { "Barrel", 150, unlocked, 8 },
    [ "kk_ins2_bipod" ] =           { "Under", 150, unlocked, 9 },
    [ "kk_ins2_vertgrip" ] =        { "Under", 150, unlocked, 10 },
    [ "kk_ins2_gl_m203" ] =         { "Under", 200, unlocked, 11 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 12 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 13 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 14 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 15 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 16 }
}
wep_att[ "cw_kk_ins2_m249" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_suppressor_sec" ] =  { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 7 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 8 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 9 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 10 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 11 }
}
wep_att[ "cw_kk_ins2_m40a1" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_scope_m40" ] =       { "Sight", 250, unlocked = true, 6 },
    [ "kk_ins2_suppressor_sec" ] =  { "Barrel", 150, unlocked, 7 },
    [ "kk_ins2_bipod" ] =           { "Under", 150, unlocked, 8 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 9 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 10 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 11 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 12 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 13 }
}
wep_att[ "cw_kk_ins2_m4a1" ] = {
    [ "bg_foldsight" ] =            { "Sight", 50, unlocked, 1 },
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 3 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 4 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 6 },
    [ "kk_ins2_suppressor_sec" ] =  { "Barrel", 150, unlocked, 7 },
    [ "kk_ins2_hoovy" ] =           { "Barrel", 150, unlocked, 8 },
    [ "kk_ins2_vertgrip" ] =        { "Under", 150, unlocked, 9 },
    [ "kk_ins2_gl_m203" ] =         { "Under", 200, unlocked, 10 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 11 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 12 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 13 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 14 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 15 }
}
wep_att[ "cw_kk_ins2_m590" ] = {
    [ "kk_ins2_kobra" ] =               { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =              { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =            { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_suppressor_shotgun" ] =  { "Barrel", 150, unlocked, 4 },
    [ "kk_ins2_vertgrip" ] =            { "Under", 150, unlocked, 5 },
    [ "kk_ins2_lam" ] =                 { "Lasers", 100, unlocked, 6 },
    [ "kk_ins2_flashlight" ] =          { "Lasers", 150, unlocked, 7 },
    [ "kk_ins2_anpeq15" ] =             { "Lasers", 200, unlocked, 8 },
    [ "am_slugrounds" ] =               { "Ammo", 200, unlocked, 9 },
    [ "am_flechetterounds" ] =          { "Ammo", 200, unlocked, 10 }
}
wep_att[ "cw_kk_ins2_mk18" ] = {
    [ "kk_ins2_kobra" ] =           { "Sight", 100, unlocked, 1 },
    [ "kk_ins2_eotech" ] =          { "Sight", 100, unlocked, 2 },
    [ "kk_ins2_aimpoint" ] =        { "Sight", 150, unlocked, 3 },
    [ "kk_ins2_elcan" ] =           { "Sight", 200, unlocked, 4 },
    [ "kk_ins2_po4" ] =             { "Sight", 200, unlocked, 5 },
    [ "kk_ins2_suppressor_sec" ] =  { "Barrel", 150, unlocked, 6 },
    [ "kk_ins2_hoovy" ] =           { "Barrel", 150, unlocked, 7 },
    [ "kk_ins2_vertgrip" ] =        { "Under", 250, unlocked, 8 },
    [ "kk_ins2_lam" ] =             { "Lasers", 100, unlocked, 9 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 150, unlocked, 10 },
    [ "kk_ins2_anpeq15" ] =         { "Lasers", 200, unlocked, 11 },
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 12 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 13 }
}
--//RedSecondaries
wep_att[ "cw_kk_ins2_m1911" ] = {
    [ "kk_ins2_lam" ] =                 { "Lasers", 100, unlocked, 1 },
    [ "kk_ins2_flashlight" ] =          { "Lasers", 150, unlocked, 2 },
    [ "kk_ins2_m6x" ] =                 { "Lasers", 200, unlocked, 3 },
    [ "kk_ins2_suppressor_pistol" ] =   { "Barrel", 150, unlocked, 4 },
    [ "kk_ins2_mag_m1911_15" ] =        { "Miscellaneous", 200, unlocked, 5 },
    [ "am_magnum" ] =                   { "Ammo", 200, unlocked, 6 },
    [ "am_matchgrade" ] =               { "Ammo", 250, unlocked, 7 }
}
wep_att[ "cw_kk_ins2_makarov" ] = {
    [ "kk_ins2_lam" ] =                 { "Lasers", 100, unlocked, 1 },
    [ "kk_ins2_flashlight" ] =          { "Lasers", 150, unlocked, 2 },
    [ "kk_ins2_m6x" ] =                 { "Lasers", 200, unlocked, 3 },
    [ "kk_ins2_suppressor_pistol" ] =   { "Barrel", 150, unlocked, 4 },
    [ "kk_ins2_mag_makarov_15" ] =      { "Miscellaneous", 200, unlocked, 5 },
    [ "am_magnum" ] =                   { "Ammo", 200, unlocked, 6 },
    [ "am_matchgrade" ] =               { "Ammo", 250, unlocked, 7 }
}
--//BlueSecondaries
wep_att[ "cw_kk_ins2_m9" ] = {
    [ "kk_ins2_lam" ] =                 { "Lasers", 100, unlocked, 1 },
    [ "kk_ins2_flashlight" ] =          { "Lasers", 150, unlocked, 2 },
    [ "kk_ins2_m6x" ] =                 { "Lasers", 200, unlocked, 3 },
    [ "kk_ins2_suppressor_pistol" ] =   { "Barrel", 150, unlocked, 4 },
    [ "am_magnum" ] =                   { "Ammo", 200, unlocked, 5 },
    [ "am_matchgrade" ] =               { "Ammo", 250, unlocked, 6 }
}
wep_att[ "cw_kk_ins2_m45" ] = {
    [ "kk_ins2_lam" ] =                 { "Lasers", 100, unlocked, 1 },
    [ "kk_ins2_flashlight" ] =          { "Lasers", 150, unlocked, 2 },
    [ "kk_ins2_m6x" ] =                 { "Lasers", 200, unlocked, 3 },
    [ "kk_ins2_suppressor_pistol" ] =   { "Barrel", 150, unlocked, 4 },
    [ "kk_ins2_mag_m45_15" ] =          { "Miscellaneous", 200, unlocked, 5 },
    [ "am_magnum" ] =                   { "Ammo", 200, unlocked, 6 },
    [ "am_matchgrade" ] =               { "Ammo", 250, unlocked, 7 }
}
--//SharedSecondaries
wep_att[ "cw_kk_ins2_revolver" ] = {
    [ "kk_ins2_lam" ] =             { "Lasers", 150, unlocked, 1 },
    [ "kk_ins2_flashlight" ] =      { "Lasers", 200, unlocked, 2 },
    [ "kk_ins2_revolver_mag" ] =    { "Miscellaneous", 200, unlocked, 3 }, --Find the type!
    [ "am_magnum" ] =               { "Ammo", 200, unlocked, 4 },
    [ "am_matchgrade" ] =           { "Ammo", 250, unlocked, 5 }
}